# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-12 23:37
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('message', models.TextField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_author', to=settings.AUTH_USER_MODEL)),
                ('recipient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_recipient', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Journey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField(default=0, help_text='Price for whole journey from beginning to end.')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date/time of start of journey')),
                ('approx', models.BooleanField(default='', verbose_name='Driver is not sure about exact time of departure')),
                ('approx_note', models.CharField(blank=True, max_length=100, verbose_name='If approx is applied, this can be used for short note to departure')),
                ('currency', models.CharField(choices=[('CZK', 'Kc'), ('EUR', 'Eur')], default='CZK', max_length=3)),
                ('comments', models.ManyToManyField(blank=True, to='web.Comment')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='JourneyWaypoints',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, help_text='Note about the place, i.e. corner of cross.', max_length=100, null=True)),
                ('output_only', models.BooleanField(default=False, help_text='Waypoting is for leaving only.')),
                ('order', models.IntegerField(default=0, verbose_name='Order number from start')),
                ('segment_price', models.FloatField(blank=True, default=None, help_text='Price between previous and this waypoint (currency is same as set in journey).', null=True, verbose_name='Partial price of journey')),
                ('journey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.Journey')),
            ],
        ),
        migrations.CreateModel(
            name='Passanger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('subscr', 'Assigned'), ('unsubs', 'Unsubscribed'), ('reject', 'Rejected by driver')], default='subscr', max_length=6)),
                ('journey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.Journey')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(blank=True, max_length=13)),
                ('reputation', models.IntegerField(blank=True, default=0)),
                ('mojeid', models.CharField(blank=True, max_length=100)),
                ('num_journeys', models.IntegerField(blank=True, default=0)),
                ('driven_km', models.IntegerField(blank=True, default=0)),
                ('drive_years', models.IntegerField(blank=True, default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Waypoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100)),
                ('lat', models.FloatField(default=0, verbose_name='Lattitude')),
                ('long', models.FloatField(default=0, verbose_name='Longtitude')),
            ],
        ),
        migrations.AddField(
            model_name='journeywaypoints',
            name='passangers',
            field=models.ManyToManyField(blank=True, to='web.Passanger'),
        ),
        migrations.AddField(
            model_name='journeywaypoints',
            name='waypoint',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.Waypoint'),
        ),
        migrations.AddField(
            model_name='journey',
            name='waypoints',
            field=models.ManyToManyField(through='web.JourneyWaypoints', to='web.Waypoint'),
        ),
        migrations.AlterUniqueTogether(
            name='journeywaypoints',
            unique_together=set([('journey', 'order')]),
        ),
    ]
