# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-10 21:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='highway_mark',
            new_name='toll_sticker',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='mojeid',
        ),
        migrations.AddField(
            model_name='journey',
            name='car',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='web.Car'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='passanger',
            name='change_timestamp',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='drive_years',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='driven_km',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='num_journeys',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='reputation',
            field=models.IntegerField(default=0),
        ),
    ]
