# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-24 06:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('owner', models.IntegerField(default=None)),
                ('register', models.CharField(blank=True, default=None, max_length=20)),
                ('color', models.CharField(max_length=10)),
                ('wifi_on_board', models.BooleanField(default=False)),
                ('animals_allowed', models.BooleanField(default=False)),
                ('highway_mark', models.BooleanField(default=False)),
                ('smoking_allowed', models.BooleanField(default=False)),
                ('air_conditioning', models.BooleanField(default=True)),
            ],
        ),
    ]
