# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-14 12:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='journey',
            name='price',
        ),
        migrations.AddField(
            model_name='journey',
            name='seats',
            field=models.IntegerField(default=0, verbose_name='Amount of availabe seats for this journey'),
        ),
    ]
