# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-23 23:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_auto_20160214_1254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journey',
            name='seats',
            field=models.IntegerField(default=0, verbose_name='Amount of available seats for this journey'),
        ),
    ]
