# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-11 23:14
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('message', models.TextField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_author', to=settings.AUTH_USER_MODEL)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_recipient', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Journey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField(default=0)),
                ('currency', models.CharField(default='CZK', max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='JourneyWaypoints',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0, verbose_name='Number of stop from start point')),
                ('journey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.Journey')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(blank=True, max_length=13, verbose_name='Phone numberr')),
                ('reputation', models.IntegerField(blank=True, default=0)),
                ('modeid', models.CharField(blank=True, max_length=100)),
                ('num_journeys', models.IntegerField(blank=True, default=0)),
                ('driven_km', models.IntegerField(blank=True, default=0)),
                ('drive_years', models.IntegerField(blank=True, default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Waypoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100)),
                ('label', models.CharField(blank=True, default='', max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='journeywaypoints',
            name='waypoint',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.Waypoint'),
        ),
        migrations.AddField(
            model_name='journey',
            name='city_from',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wpt_from', to='web.Waypoint'),
        ),
        migrations.AddField(
            model_name='journey',
            name='city_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wpt_to', to='web.Waypoint'),
        ),
        migrations.AddField(
            model_name='journey',
            name='comments',
            field=models.ManyToManyField(blank=True, to='web.Comment'),
        ),
        migrations.AddField(
            model_name='journey',
            name='driver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
