# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-11 23:20
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='journey',
            name='approx',
            field=models.BooleanField(default='', verbose_name='Driver is not sure about exact time of departure'),
        ),
        migrations.AddField(
            model_name='journey',
            name='approx_note',
            field=models.CharField(blank=True, max_length=100, verbose_name='If approx is applied, this can be used for short note to departure'),
        ),
        migrations.AddField(
            model_name='journey',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2016, 2, 11, 23, 20, 43, 417232), verbose_name='Date/time of start of journey'),
        ),
        migrations.AddField(
            model_name='journey',
            name='waypoints',
            field=models.ManyToManyField(through='web.JourneyWaypoints', to='web.Waypoint'),
        ),
    ]
