# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-12 09:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_auto_20160212_0905'),
    ]

    operations = [
        migrations.RenameField(
            model_name='membership',
            old_name='group',
            new_name='group1',
        ),
        migrations.RenameField(
            model_name='membership',
            old_name='person',
            new_name='person1',
        ),
    ]
