# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-12 09:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_journeywaypoints_partial_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='waypoint',
            name='lat',
            field=models.FloatField(default=0, verbose_name='Lattitude'),
        ),
        migrations.AddField(
            model_name='waypoint',
            name='long',
            field=models.FloatField(default=0, verbose_name='Longtitude'),
        ),
        migrations.AlterField(
            model_name='journeywaypoints',
            name='order',
            field=models.IntegerField(default=0, verbose_name='Number of stop from start city'),
        ),
        migrations.AlterUniqueTogether(
            name='journeywaypoints',
            unique_together=set([('journey', 'waypoint', 'order')]),
        ),
    ]
