# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-12 11:09
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('web', '0008_auto_20160212_0941'),
    ]

    operations = [
        migrations.CreateModel(
            name='Passanger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('subscr', 'Assigned to the journey'), ('unsubs', 'Unsubscribed to the journey'), ('reject', 'Rejected by driver')], default='subscr', max_length=6)),
            ],
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='modeid',
            new_name='mojeid',
        ),
        migrations.RemoveField(
            model_name='journey',
            name='city_from',
        ),
        migrations.RemoveField(
            model_name='journey',
            name='city_to',
        ),
        migrations.AddField(
            model_name='journeywaypoints',
            name='segment_price',
            field=models.FloatField(blank=True, default=None, help_text='Price between previous and this waypoint (currency is same as set in journey).', null=True, verbose_name='Partial price of journey'),
        ),
        migrations.AddField(
            model_name='waypoint',
            name='output_only',
            field=models.BooleanField(default=False, help_text='Waypoting is for leaving only.'),
        ),
        migrations.AlterField(
            model_name='journeywaypoints',
            name='order',
            field=models.IntegerField(default=0, verbose_name='Order number from start'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=13),
        ),
        migrations.RemoveField(
            model_name='journeywaypoints',
            name='partial_price',
        ),
        migrations.AddField(
            model_name='journeywaypoints',
            name='passangers',
            field=models.ManyToManyField(to='web.Passanger'),
        ),
        migrations.AlterUniqueTogether(
            name='journeywaypoints',
            unique_together=set([('journey', 'order')]),
        ),
        migrations.AddField(
            model_name='passanger',
            name='journey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.Journey'),
        ),
        migrations.AddField(
            model_name='passanger',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
