# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-12 11:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0009_auto_20160212_1109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journey',
            name='currency',
            field=models.CharField(choices=[('CZK', 'Kc'), ('EUR', 'Eur')], default='CZK', max_length=3),
        ),
        migrations.AlterField(
            model_name='journey',
            name='price',
            field=models.FloatField(default=0, help_text='Price for whole journey from beginning to end.'),
        ),
    ]
