# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-12 11:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0011_auto_20160212_1138'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='waypoint',
            name='label',
        ),
        migrations.AddField(
            model_name='journeywaypoints',
            name='label',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
