# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-12 12:35
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0012_auto_20160212_1143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='recipient',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_recipient', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='passanger',
            name='state',
            field=models.CharField(choices=[('subscr', 'Assigned'), ('unsubs', 'Unsubscribed'), ('reject', 'Rejected by driver')], default='subscr', max_length=6),
        ),
    ]
