# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-12 12:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0015_auto_20160212_1253'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='journeywaypoints',
            name='passangers',
        ),
        migrations.AddField(
            model_name='journeywaypoints',
            name='passangers',
            field=models.ManyToManyField(to='web.Passanger'),
        ),
    ]
